theme: jekyll-theme-experiment

title: Oleksii Merkulov 🇺🇦
description: >-
  Greetings!</br>
  My name is Oleksii(Alex) Merkulov.
  I am a Ruby on Rails developer with over 10 years of experience and
  can help you with your project of any complexity.</br>
  I am ready for various tasks:</br>
  - fix some problems or issues;</br>
  - develop from scratch Rails application (any other Ruby frameworks);</br>
  - integrate any Third Party API;</br>
  - configure and deploy the application to any cloud service
  (Heroku, AWS, DigitalOcean, etc.);</br>

header_pages:
  - index.md
  - portfolio.md

jekyll-theme-experiment:
  about:
    avatar: /assets/images/profile.png

  portfolio:
    title: My Portfolio
    projects:

  tools:
    title: Tools and Experience 
    icons:
      - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
      - relative_url: /assets/icons/heroku/heroku-plain.svg
      - relative_url: /assets/icons/git/git-original.svg
      - relative_url: /assets/icons/github/github-original.svg

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - .gitignore
